# Generated by Django 3.1.5 on 2021-01-18 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0004_auto_20210117_2222'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('sides', models.IntegerField(choices=[(4, 'Four'), (6, 'Six'), (8, 'Eight'), (10, 'Ten'), (12, 'Twelve'), (20, 'Twenty'), (100, 'OneHundred')])),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiceSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eight_sided', models.ForeignKey(blank=True, limit_choices_to={'sides': 8}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eight_sided', to='dice.dice')),
                ('four_sided', models.ForeignKey(blank=True, limit_choices_to={'sides': 4}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='four_sided', to='dice.dice')),
                ('one_hundred_sided', models.ForeignKey(blank=True, limit_choices_to={'sides': 100}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='one_hundred_sided', to='dice.dice')),
                ('six_sided', models.ForeignKey(blank=True, limit_choices_to={'sides': 6}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='six_sided', to='dice.dice')),
                ('ten_sided', models.ForeignKey(blank=True, limit_choices_to={'sides': 10}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ten_sided', to='dice.dice')),
                ('twelve_sided', models.ForeignKey(blank=True, limit_choices_to={'sides': 12}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='twelve_sided', to='dice.dice')),
                ('twenty_sided', models.ForeignKey(blank=True, limit_choices_to={'sides': 20}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='twenty_sided', to='dice.dice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiceRoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('sides', models.IntegerField(choices=[(4, 'Four'), (6, 'Six'), (8, 'Eight'), (10, 'Ten'), (12, 'Twelve'), (20, 'Twenty'), (100, 'OneHundred')])),
                ('image', models.ImageField(upload_to='')),
                ('die', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dice_rolls', to='dice.dice')),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.gamesession')),
            ],
        ),
    ]
