# Generated by Django 3.1.5 on 2021-01-29 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dice',
            name='luckiness',
            field=models.IntegerField(choices=[(0, 'cold'), (1, 'neutral'), (2, 'hot')], default=1),
        ),
    ]
