# Generated by Django 3.1.5 on 2021-01-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dice', '0002_dice_luckiness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diceroll',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
