# Generated by Django 3.1.5 on 2021-01-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaign_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='end_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
