# Generated by Django 3.1.5 on 2021-01-18 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dice', '0001_initial'),
        ('campaigns', '0004_auto_20210117_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='diceset',
            field=models.ManyToManyField(blank=True, to='dice.DiceSet'),
        ),
    ]
