# Generated by Django 3.1.5 on 2021-01-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_campaign_diceset'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='current_session',
            field=models.BooleanField(default=False),
        ),
    ]
